theme: jekyll-theme-slate
url:  https://kdboller.github.io/
title:  Kevin Boller's personal site and blog.
description:  <a href="https://kdboller.github.io/">Home</a> | <a href="https://kdboller.github.io/about">About</a> | 
<a href="https://kdboller.github.io/blog">Blog</a>
