baseURL = "https://kdboller.github.io/"
languageCode = "en-us"
title = "Data Informed Narratives"
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[pagination]
  pagerSize = 5

[params]
  env = "production"
  author = "Kevin Boller"
  description = "Sports, technology, data analytics, and personal finance."
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowToc = true

  [params.homeInfoParams]
    Title = "Hi, I'm Kevin Boller"
    Content = "Advisor, operator, investor, and sports fanatic. Deep financial and analytical background, working at the intersection of data, analytics, and AI for several years. 
    \n\nMy focus is on building the data and AI infrastructure that grows revenue, generates operational efficiency, and drives enterprise-wide adoption across an organization.
    \n\nHaving executed at the intersection of finance, product, and business intelligence, I understand what it takes to move from insight to action at scale.
"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/kevinboller"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/kdboller"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/kevinboller"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "investing"
    name = "Investing"
    url = "/investing/"
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
